version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/aws-test-project-1.0-SNAPSHOT.war
    - appspec.yml
  discard-paths: yes